# Generated by Django 3.2.9 on 2023-11-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ageis_app', '0003_clients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name_plural': 'Cients/Company'},
        ),
        migrations.AddField(
            model_name='extendedusermodel',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
