# Generated by Django 4.2.7 on 2023-11-29 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ageis_app', '0004_auto_20231116_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extendedusermodel', to='ageis_app.extendedusermodel'),
        ),
    ]
