# Generated by Django 4.2.7 on 2023-11-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ageis_app', '0007_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Job categories',
            },
        ),
    ]
