# Generated by Django 4.2.7 on 2023-11-30 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ageis_app', '0012_jobtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_post_date', models.DateField(auto_now_add=True)),
                ('job_title', models.CharField(max_length=50)),
                ('company_logo', models.ImageField(upload_to='companylogo')),
                ('company_email', models.EmailField(max_length=254)),
                ('end_date', models.DateField()),
                ('job_des', models.TextField()),
                ('skills', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('salary', models.CharField(max_length=25)),
                ('languages', models.CharField(max_length=100)),
                ('website_link', models.URLField()),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ageis_app.clients')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ageis_app.country')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ageis_app.district')),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ageis_app.jobcategories')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ageis_app.jobtype')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ageis_app.state')),
            ],
        ),
    ]
