# Generated by Django 4.2.7 on 2023-12-04 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ageis_app', '0014_jobs_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('applied_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ageis_app.jobs')),
                ('applied_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ageis_app.extendedusermodel')),
            ],
        ),
    ]
