# Generated by Django 4.2.7 on 2023-12-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ageis_app', '0017_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
    ]
