# Generated by Django 4.2.7 on 2023-12-08 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ageis_app', '0018_demomodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemoModel',
        ),
    ]
