# Generated by Django 4.2.8 on 2023-12-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ageis_app', '0019_delete_demomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=65, null=True)),
                ('name', models.CharField(max_length=191)),
                ('title', models.CharField(max_length=100, null=True)),
                ('company', models.CharField(max_length=191, null=True)),
                ('description', models.TextField(null=True)),
                ('country', models.IntegerField(default=0)),
                ('zip', models.CharField(max_length=15, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('assigned', models.IntegerField(default=0)),
                ('dateadded', models.DateTimeField(auto_now_add=True)),
                ('from_form_id', models.IntegerField(default=0)),
                ('status', models.IntegerField(null=True)),
                ('source', models.IntegerField(null=True)),
                ('lastcontact', models.DateTimeField(null=True)),
                ('dateassigned', models.DateField(null=True)),
                ('last_status_change', models.DateTimeField(null=True)),
                ('addedfrom', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=100, null=True)),
                ('website', models.CharField(max_length=150, null=True)),
                ('leadorder', models.IntegerField(default=1, null=True)),
                ('phonenumber', models.CharField(max_length=50, null=True)),
                ('date_converted', models.DateTimeField(null=True)),
                ('lost', models.IntegerField(default=0)),
                ('junk', models.IntegerField(default=0)),
                ('last_lead_status', models.IntegerField(default=0)),
                ('is_imported_from_email_integration', models.IntegerField(default=0)),
                ('email_integration_uid', models.CharField(max_length=30, null=True)),
                ('is_public', models.IntegerField(default=0)),
                ('default_language', models.CharField(max_length=40, null=True)),
                ('client_id', models.IntegerField(default=0)),
                ('lead_value', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'tblleads',
            },
        ),
    ]
