# Generated by Django 4.2.7 on 2024-01-08 05:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ageis_app", "0021_auto_20240105_1047"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clients",
            options={"verbose_name_plural": "Clients/Company"},
        ),
    ]
