# Generated by Django 4.2.7 on 2024-01-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ageis_app", "0023_rename_company_name_jobs_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendedusermodel",
            name="comapany_univercity",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="extendedusermodel",
            name="position",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
