# Generated by Django 4.2.7 on 2024-01-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ageis_app", "0024_extendedusermodel_comapany_univercity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendedusermodel",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos"),
        ),
    ]
