# Generated by Django 4.2.8 on 2024-03-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ageis_app', '0025_extendedusermodel_profile_photo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='country',
            table='ageis_app_country',
        ),
    ]
