# Generated by Django 4.2.7 on 2024-04-02 05:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ageis_app", "0026_clientacquisitionsource_invoice_jobposting_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="client",
        ),
        migrations.RemoveField(
            model_name="jobposting",
            name="client",
        ),
        migrations.RemoveField(
            model_name="jobposting",
            name="source",
        ),
        migrations.RemoveField(
            model_name="offerletter",
            name="candidate",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="invoice",
        ),
        migrations.RemoveField(
            model_name="shortlistedcandidate",
            name="candidate",
        ),
        migrations.RemoveField(
            model_name="shortlistedcandidate",
            name="job",
        ),
        migrations.DeleteModel(
            name="CandidateApplication",
        ),
        migrations.DeleteModel(
            name="ClientAcquisitionSource",
        ),
        migrations.DeleteModel(
            name="Invoice",
        ),
        migrations.DeleteModel(
            name="JobPosting",
        ),
        migrations.DeleteModel(
            name="OfferLetter",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="ShortlistedCandidate",
        ),
    ]
