# Generated by Django 4.2.7 on 2024-04-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ageis_app", "0027_remove_invoice_client_remove_jobposting_client_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appliedjobs",
            name="is_shortlisted",
            field=models.BooleanField(default=False),
        ),
    ]
