# Generated by Django 4.2.7 on 2024-04-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ageis_app", "0028_appliedjobs_is_shortlisted"),
    ]

    operations = [
        migrations.AddField(
            model_name="appliedjobs",
            name="is_invited",
            field=models.BooleanField(default=False),
        ),
    ]
