# Generated by Django 4.2.7 on 2024-04-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ageis_app", "0031_alter_appliedjobs_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="appliedjobs",
            name="offer_letter",
            field=models.FileField(blank=True, null=True, upload_to="offer_letters"),
        ),
    ]
