# Generated by Django 4.2.8 on 2024-04-08 08:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ageis_app", "0026_alter_country_table"),
        ("ageis_app", "0033_appliedjobs_handeled_by_alter_appliedjobs_result"),
    ]

    operations = []
