# Generated by Django 4.2.7 on 2024-05-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ageis_app",
            "0035_alter_extendedusermodel_phone_alter_jobs_experience_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="website_link",
            field=models.CharField(max_length=100),
        ),
    ]
