# Generated by Django 4.2.7 on 2024-08-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ageis_app", "0037_recentlysearchedjobs"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobs",
            name="application_count",
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
