# Generated by Django 4.2.7 on 2024-08-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ageis_app", "0038_jobs_application_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="application_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
