# Generated by Django 4.2.7 on 2024-08-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ageis_app", "0039_alter_jobs_application_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="application_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
