# Generated by Django 4.2.7 on 2024-08-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ageis_app", "0040_alter_jobs_application_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcategories",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="job_categories/"),
        ),
    ]
