# Generated by Django 5.0.8 on 2024-08-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ageis_app', '0041_jobcategories_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='experience',
            unique_together={('user', 'company', 'position', 'start_date')},
        ),
        migrations.AlterUniqueTogether(
            name='qualification',
            unique_together={('user', 'degree', 'institution')},
        ),
    ]
