# Generated by Django 4.2.7 on 2024-08-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ageis_app",
            "0042_extendedusermodel_country_extendedusermodel_district_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="extendedusermodel",
            name="relocate",
            field=models.BooleanField(default=False),
        ),
    ]
