# Generated by Django 4.2.7 on 2024-08-24 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ageis_app", "0043_extendedusermodel_relocate"),
    ]

    operations = [
        migrations.AddField(
            model_name="appliedjobs",
            name="created_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
