# Generated by Django 4.2.7 on 2024-08-24 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ageis_app", "0044_appliedjobs_created_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appliedjobs",
            name="created_time",
        ),
    ]
