# Generated by Django 4.2.7 on 2024-08-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ageis_app", "0045_remove_appliedjobs_created_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobs",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
