# Generated by Django 4.2.7 on 2024-08-26 05:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ageis_app", "0042_alter_experience_unique_together_and_more"),
        ("ageis_app", "0046_jobs_is_active"),
    ]

    operations = []
