# Generated by Django 4.2.7 on 2024-08-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ageis_app", "0048_alter_appliedjobs_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="experience",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
