# Generated by Django 4.2.7 on 2024-08-31 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ageis_app", "0049_alter_jobs_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="experience",
            field=models.CharField(max_length=100),
        ),
    ]
