# Generated by Django 4.2.7 on 2024-08-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ageis_app", "0051_extendedusermodel_dob_extendedusermodel_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendedusermodel",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extendedusermodel",
            name="current_company",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="extendedusermodel",
            name="current_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extendedusermodel",
            name="currently_working",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="extendedusermodel",
            name="discription",
            field=models.TextField(blank=True, null=True),
        ),
    ]
